using System.Text;
using OPP3;
Console.OutputEncoding =Encoding.UTF8;
int n1 = 5;
int n2 = 10;
Console.WriteLine($"Tong tu 1 toi {n1}={n1.TongTu1toiN()}");
Console.WriteLine($"Tong tu 1 toi {n2}={n2.TongTu1toiN()}");
Console.WriteLine($"Tong tu 1 toi 8 = " + 8.TongTu1toiN());
Console.WriteLine("8+7=" + 8.Cong(7));
int[]M= new int[8];
M.Taomang();
Console.WriteLine("Mang sau khi tao ngau nhien:");
M.XuatMang();
M.Sapxepmangtangdan();
Console.WriteLine("sap xep mau tang dan:");
M.XuatMang();
int[] M2 = M.SapXepMangGiamDan();
Console.WriteLine("sap xep mau giam dan:");
M.XuatMang();